debug:
  verbose: true

server:
  listen: 8080
  dirs:
    - control
    - preset
    - shader
    - image
    - data

  index: control/controls.md

  persist: data/persist.yaml

  page:
    title: VCT Loopin Apr 2017

    nav:
      - title: Intro
        page: control/controls.md
      - title: Kinascii
        page: control/kinascii.md
      - title: Kinect
        page: control/kinect.md
      - title: Extras
        page: control/extras.md
